### ISSUE TITLE
Please merge the `test-suite` branch into `json`.

### ISSUE THREAD

**Issue by siko1056** [Abdallah-Elshamy/octave#6]
@Abdallah-Elshamy Thank you for your continued work on the JSON project.  I think the number of branches in your repo should not exceed one.  How can I run your test files

* `test/json/jsonXXcodetest.m`

together with your work on

* `libinterp/corefcn/jsondecode.cc`

My idea for the end of GSoC is, that all your changes are accumulated in a feature branch "json", that is converted into a pull request, that can be exported to be merged into Octave.

**Comment by Abdallah-Elshamy** [comment]
I didn't add the tests as they would be converted into BIST at the end of the project. I totally missed the part of running them now. Thanks for mentioning this. I merged the `lib-test` (as it has the modifications to run the tests on Octave) branch into the `json` branch in 6403002.

**Comment by siko1056** [comment]
@Abdallah-Elshamy sorry for reviewing this merge quite late.

Merging `lib-test` was **not** the intended action to do.  Now the test suite in the `json` branch is neither Octave nor Matlab conform :scream: Like written in the headline `test-suite` has the Matlab conform tests that should be translated to a proper Octave test suite (see https://octave.org/doc/v5.2.0/Test-Functions.html for details or other examples in Octave's test directory).

**Comment by siko1056** [comment]
@Abdallah-Elshamy I think now I understand why you chose `lib-test`, but this is going a slightly wrong direction :thinking:   There you created with lots of effort an own custom test runner system, e.g.

```octave
try
  json = '["str", 5, null, true]';
  exp  = {'str'; 5; []; true};
  act  = jsondecode (json);
  assert (isequal (exp, act));
catch
  printf('test 1 failed\n');
  failed_tests_num +=1;
end_try_catch
```

If you transform `jsonXXcodetest.m` into proper Octave test files, all this burden is taken away from you and to run it in Matlab, you just have to do something like "Replace all `%!` with nothing".

I will monitor your changes daily until we are back on the right schedule.  Please keep my updated by daily commits here.

**Comment by Abdallah-Elshamy** [comment]
@siko1056  I transformed the test suite into Octave test files on the `test-suite` branch here 5676558

I removed the last commit in the `json` branch (the one I merged the `lib-test` branch into `json` branch) and merged it with the `test-suite` branch in this commit e8b9aa2 

I will also update my last blog post to conform to the new changes.

If there is any thing else, please let me know and thanks for your time.

**Comment by siko1056** [comment]
Thank you @Abdallah-Elshamy  for the changes, now everything looks right :wink:
